--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-05-14 22:58:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 862 (class 1247 OID 16672)
-- Name: questions_correctanswer_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.questions_correctanswer_enum AS ENUM (
    'A',
    'B',
    'C',
    'D'
);


ALTER TYPE public.questions_correctanswer_enum OWNER TO postgres;

--
-- TOC entry 865 (class 1247 OID 16682)
-- Name: users_selectedtheme_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.users_selectedtheme_enum AS ENUM (
    'light',
    'dark'
);


ALTER TYPE public.users_selectedtheme_enum OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16688)
-- Name: gamedifficulty; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gamedifficulty (
    "gameDifficultyId" integer NOT NULL,
    name character varying(30) DEFAULT NULL::character varying
);


ALTER TABLE public.gamedifficulty OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16687)
-- Name: gamedifficulty_gameDifficultyId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gamedifficulty ALTER COLUMN "gameDifficultyId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."gamedifficulty_gameDifficultyId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16695)
-- Name: gamehistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gamehistory (
    "gameId" integer NOT NULL,
    "playerId" integer,
    "gameDate" date,
    scorepoint integer,
    "questionScore" integer,
    "playerAnswers" integer,
    "gameDifficultyId" integer
);


ALTER TABLE public.gamehistory OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16694)
-- Name: gamehistory_gameId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gamehistory ALTER COLUMN "gameId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."gamehistory_gameId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16701)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    "notificationId" integer NOT NULL,
    "userId" integer,
    "createdAt" timestamp without time zone,
    message character varying(255) NOT NULL
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16700)
-- Name: notifications_notificationId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN "notificationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."notifications_notificationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16707)
-- Name: playeranswers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.playeranswers (
    "playerAnswersId" integer NOT NULL,
    "playerAnswers" character varying(50) NOT NULL,
    "answersCheck" character varying(50) NOT NULL
);


ALTER TABLE public.playeranswers OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16706)
-- Name: playeranswers_playerAnswersId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.playeranswers ALTER COLUMN "playerAnswersId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."playeranswers_playerAnswersId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16713)
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questions (
    "questionId" integer NOT NULL,
    content character varying(255) NOT NULL,
    "answerA" character varying(50) DEFAULT NULL::character varying,
    "answerB" character varying(50) DEFAULT NULL::character varying,
    "answerC" character varying(50) DEFAULT NULL::character varying,
    "answerD" character varying(50) DEFAULT NULL::character varying,
    "correctAnswer" public.questions_correctanswer_enum,
    "topicId" integer NOT NULL,
    "difficultyId" integer NOT NULL
);


ALTER TABLE public.questions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16712)
-- Name: questions_questionId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.questions ALTER COLUMN "questionId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."questions_questionId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16723)
-- Name: ranking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ranking (
    "playerId" integer NOT NULL,
    points integer NOT NULL,
    "rankId" integer NOT NULL
);


ALTER TABLE public.ranking OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16729)
-- Name: ranks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ranks (
    "rankId" integer NOT NULL,
    requirement integer,
    name character varying(30) DEFAULT NULL::character varying,
    "lossPoints" integer NOT NULL,
    "winPoints" integer NOT NULL
);


ALTER TABLE public.ranks OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16728)
-- Name: ranks_rankId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ranks ALTER COLUMN "rankId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ranks_rankId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16736)
-- Name: topics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topics (
    "topicId" integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.topics OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16735)
-- Name: topics_topicId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.topics ALTER COLUMN "topicId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."topics_topicId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16742)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    "userId" integer NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(30) NOT NULL,
    "createdAt" timestamp without time zone,
    "isAdmin" boolean NOT NULL,
    "selectedTheme" public.users_selectedtheme_enum
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16741)
-- Name: users_userId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN "userId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."users_userId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4965 (class 0 OID 16688)
-- Dependencies: 218
-- Data for Name: gamedifficulty; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gamedifficulty ("gameDifficultyId", name) FROM stdin;
1	Łatwy
2	Średni
3	Trudny
4	Trening
\.


--
-- TOC entry 4967 (class 0 OID 16695)
-- Dependencies: 220
-- Data for Name: gamehistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gamehistory ("gameId", "playerId", "gameDate", scorepoint, "questionScore", "playerAnswers", "gameDifficultyId") FROM stdin;
\.


--
-- TOC entry 4969 (class 0 OID 16701)
-- Dependencies: 222
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications ("notificationId", "userId", "createdAt", message) FROM stdin;
\.


--
-- TOC entry 4971 (class 0 OID 16707)
-- Dependencies: 224
-- Data for Name: playeranswers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.playeranswers ("playerAnswersId", "playerAnswers", "answersCheck") FROM stdin;
\.


--
-- TOC entry 4973 (class 0 OID 16713)
-- Dependencies: 226
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.questions ("questionId", content, "answerA", "answerB", "answerC", "answerD", "correctAnswer", "topicId", "difficultyId") FROM stdin;
\.


--
-- TOC entry 4974 (class 0 OID 16723)
-- Dependencies: 227
-- Data for Name: ranking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ranking ("playerId", points, "rankId") FROM stdin;
1	1300	7
2	0	1
\.


--
-- TOC entry 4976 (class 0 OID 16729)
-- Dependencies: 229
-- Data for Name: ranks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ranks ("rankId", requirement, name, "lossPoints", "winPoints") FROM stdin;
1	0	Pisklę Cienia	0	10
2	100	Młody Kruk	2	12
3	250	Obserwator Gałęzi	4	14
4	400	Szept Lasu	6	16
5	600	Strażnik Ksiąg	8	18
6	850	Kruk Zagadek	10	20
7	1100	Cień Proroctwa	12	22
8	1400	Wiedzący Kruk	14	24
9	1750	Mistrz Czarnych Piór	16	26
10	2150	Król Kruków	18	28
\.


--
-- TOC entry 4978 (class 0 OID 16736)
-- Dependencies: 231
-- Data for Name: topics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.topics ("topicId", name) FROM stdin;
1	Historia
2	Nauka i Technika
3	Kultura i Sztuka
4	Mitologia i Legendy
5	Geografia
6	Popkultura
\.


--
-- TOC entry 4980 (class 0 OID 16742)
-- Dependencies: 233
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users ("userId", username, email, password, "createdAt", "isAdmin", "selectedTheme") FROM stdin;
1	admin	admin@test.pl	admin	2025-05-14 21:16:07.889524	t	light
2	user	user@test.pl	user	2025-05-14 21:16:07.889524	f	dark
\.


--
-- TOC entry 4986 (class 0 OID 0)
-- Dependencies: 217
-- Name: gamedifficulty_gameDifficultyId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."gamedifficulty_gameDifficultyId_seq"', 4, true);


--
-- TOC entry 4987 (class 0 OID 0)
-- Dependencies: 219
-- Name: gamehistory_gameId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."gamehistory_gameId_seq"', 1, false);


--
-- TOC entry 4988 (class 0 OID 0)
-- Dependencies: 221
-- Name: notifications_notificationId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."notifications_notificationId_seq"', 1, false);


--
-- TOC entry 4989 (class 0 OID 0)
-- Dependencies: 223
-- Name: playeranswers_playerAnswersId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."playeranswers_playerAnswersId_seq"', 1, false);


--
-- TOC entry 4990 (class 0 OID 0)
-- Dependencies: 225
-- Name: questions_questionId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."questions_questionId_seq"', 1, false);


--
-- TOC entry 4991 (class 0 OID 0)
-- Dependencies: 228
-- Name: ranks_rankId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ranks_rankId_seq"', 11, true);


--
-- TOC entry 4992 (class 0 OID 0)
-- Dependencies: 230
-- Name: topics_topicId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."topics_topicId_seq"', 6, true);


--
-- TOC entry 4993 (class 0 OID 0)
-- Dependencies: 232
-- Name: users_userId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."users_userId_seq"', 2, true);


--
-- TOC entry 4794 (class 2606 OID 16693)
-- Name: gamedifficulty gamedifficulty_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gamedifficulty
    ADD CONSTRAINT gamedifficulty_pkey PRIMARY KEY ("gameDifficultyId");


--
-- TOC entry 4796 (class 2606 OID 16699)
-- Name: gamehistory gamehistory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gamehistory
    ADD CONSTRAINT gamehistory_pkey PRIMARY KEY ("gameId");


--
-- TOC entry 4798 (class 2606 OID 16705)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY ("notificationId");


--
-- TOC entry 4800 (class 2606 OID 16711)
-- Name: playeranswers playeranswers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.playeranswers
    ADD CONSTRAINT playeranswers_pkey PRIMARY KEY ("playerAnswersId");


--
-- TOC entry 4802 (class 2606 OID 16721)
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY ("questionId");


--
-- TOC entry 4804 (class 2606 OID 16727)
-- Name: ranking ranking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ranking
    ADD CONSTRAINT ranking_pkey PRIMARY KEY ("playerId");


--
-- TOC entry 4806 (class 2606 OID 16734)
-- Name: ranks ranks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ranks
    ADD CONSTRAINT ranks_pkey PRIMARY KEY ("rankId");


--
-- TOC entry 4808 (class 2606 OID 16740)
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY ("topicId");


--
-- TOC entry 4810 (class 2606 OID 16746)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY ("userId");


--
-- TOC entry 4811 (class 2606 OID 16747)
-- Name: gamehistory gamehistory_ibfk_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gamehistory
    ADD CONSTRAINT gamehistory_ibfk_1 FOREIGN KEY ("playerId") REFERENCES public.users("userId");


--
-- TOC entry 4812 (class 2606 OID 16752)
-- Name: gamehistory gamehistory_ibfk_2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gamehistory
    ADD CONSTRAINT gamehistory_ibfk_2 FOREIGN KEY ("gameDifficultyId") REFERENCES public.gamedifficulty("gameDifficultyId");


--
-- TOC entry 4813 (class 2606 OID 16757)
-- Name: gamehistory gamehistory_ibfk_3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gamehistory
    ADD CONSTRAINT gamehistory_ibfk_3 FOREIGN KEY ("playerAnswers") REFERENCES public.playeranswers("playerAnswersId");


--
-- TOC entry 4814 (class 2606 OID 16762)
-- Name: notifications notifications_ibfk_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_ibfk_1 FOREIGN KEY ("userId") REFERENCES public.users("userId");


--
-- TOC entry 4815 (class 2606 OID 16767)
-- Name: questions questions_ibfk_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_ibfk_1 FOREIGN KEY ("topicId") REFERENCES public.topics("topicId");


--
-- TOC entry 4816 (class 2606 OID 16772)
-- Name: questions questions_ibfk_2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_ibfk_2 FOREIGN KEY ("difficultyId") REFERENCES public.gamedifficulty("gameDifficultyId");


--
-- TOC entry 4817 (class 2606 OID 16777)
-- Name: ranking ranking_ibfk_1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ranking
    ADD CONSTRAINT ranking_ibfk_1 FOREIGN KEY ("playerId") REFERENCES public.users("userId");


--
-- TOC entry 4818 (class 2606 OID 16782)
-- Name: ranking ranking_ibfk_2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ranking
    ADD CONSTRAINT ranking_ibfk_2 FOREIGN KEY ("rankId") REFERENCES public.ranks("rankId");


-- Completed on 2025-05-14 22:58:46

--
-- PostgreSQL database dump complete
--

